### ISSUE TITLE
no data found 

### ISSUE THREAD

**Issue by sushanths5454** [mlomnitz/CompressionGAN#2]
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Training on dataset faces
Traceback (most recent call last):
  File "scripts/train.py", line 119, in <module>
    main()
  File "scripts/train.py", line 116, in main
    train(config_train, args)
  File "scripts/train.py", line 30, in train
    paths = Data.load_dataframe(directories.train)
  File "/usr/local/lib/python3.6/dist-packages/CompressionGAN-0.0.1-py3.6.egg/comp_gan/data.py", line 11, in load_dataframe
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/pytables.py", line 347, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File data/faces_paths_train.d5 does not exist

**Comment by mlomnitz** [comment]
The file containing the indexed data was not uploaded to save space.  You can recreate it using the notebook in:
CompressionGAN/notebooks/ImagePreprocessing_07_2018.ipynb
